# Generated by Django 5.1.6 on 2025-02-18 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_app', '0003_remove_userprofile_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hos_app.department'),
        ),
    ]
