# Generated by Django 5.1.6 on 2025-02-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_app', '0005_alter_doctor_working_days_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
