# Generated by Django 5.1.6 on 2025-02-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_app', '0006_doctor_experience_doctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=16, null=True),
        ),
    ]
