# Generated by Django 5.1.6 on 2025-02-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_app', '0007_alter_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
